Repository pmmp/PocketMine-MP, pull requests merged in 2018-06, with the labels that each got.

#2226 Remove double use of spl_object_hash
  src/pocketmine/inventory/transaction/InventoryTransaction.php
Labels: Category: Core, PR: Bug Fix

#2176 Implemented an InventoryEventProcessor, fixes #1986
  src/pocketmine/entity/Human.php
  src/pocketmine/entity/Living.php
  src/pocketmine/inventory/ArmorInventory.php
  src/pocketmine/inventory/ArmorInventoryEventProcessor.php
  src/pocketmine/inventory/BaseInventory.php
  src/pocketmine/inventory/EntityInventoryEventProcessor.php
  src/pocketmine/inventory/FurnaceInventory.php
  src/pocketmine/inventory/Inventory.php
  src/pocketmine/inventory/InventoryEventProcessor.php
  src/pocketmine/inventory/PlayerInventory.php
  src/pocketmine/tile/Furnace.php
Labels: Category: API, Category: Core, PR: Bug Fix, Status: Insufficiently Tested

#2193 PluginBase::getResources() returns associative array
  src/pocketmine/plugin/PluginBase.php
Labels: Category: API

#2259 Implemented Infinity enchantment
  src/pocketmine/item/Bow.php
  src/pocketmine/item/enchantment/Enchantment.php
Labels: Category: Gameplay, PR: Contribution

#2258 Implemented Thorns enchantment
  src/pocketmine/entity/Living.php
  src/pocketmine/item/enchantment/Enchantment.php
Labels: Category: Gameplay, PR: Contribution

#2267 reorganize and optimize start.sh
  start.sh
Labels: Category: Other, PR: Contribution

#2268 Remove a whole bunch of crap from the `Plugin` public interface
  src/pocketmine/plugin/Plugin.php
  src/pocketmine/plugin/PluginBase.php
  src/pocketmine/plugin/PluginManager.php
Labels: BC break, Category: API, PR: Contribution, PR: Optimization
