Repository pmmp/PocketMine-MP, pull requests merged in 2018-10, with the labels that each got.

#2472 PluginManager: Stop catching exceptions thrown by event handlers
  src/pocketmine/plugin/PluginManager.php
Labels: Category: API, Category: Core, PR: Bug Fix

#2477 Revamp MetadataStore API
  src/pocketmine/metadata/BlockMetadataStore.php
  src/pocketmine/metadata/EntityMetadataStore.php
  src/pocketmine/metadata/LevelMetadataStore.php
  src/pocketmine/metadata/MetadataStore.php
  src/pocketmine/metadata/PlayerMetadataStore.php
Labels: Category: API, PR: Cosmetic, PR: Optimization

#2489 SubChunk: implement branchless read/write for nibble arrays
  src/pocketmine/level/format/SubChunk.php
Labels: Category: Core, PR: Optimization

#2493 Improve async task collection algorithm
  src/pocketmine/scheduler/AsyncPool.php
  src/pocketmine/scheduler/AsyncTask.php
Labels: Category: Core, PR: Optimization

#2496 Fix #2436
  src/pocketmine/block/Door.php
Labels: Category: Gameplay, PR: Bug Fix
