Repository pmmp/PocketMine-MP, pull requests merged in 2018-02, with the labels that each got.

#2017 Player: fix respawning after rage-quit on death
  src/pocketmine/Player.php
  src/pocketmine/entity/Entity.php
Labels: Category: Core, Category: Gameplay, PR: Bug Fix, Priority: High

#1929 Implemented critical hits
  src/pocketmine/Player.php
  src/pocketmine/event/entity/EntityDamageEvent.php
Labels: Category: Gameplay, PR: Contribution

#2043 Expose plugin.yml contents to plugins with PluginDescription::getMap()
  src/pocketmine/plugin/PluginDescription.php
Labels: Category: Plugin API, PR: Contribution

#2054 Added hasEffects() function
  src/pocketmine/entity/Living.php
Labels: Category: Plugin API, PR: Contribution

#2057 Allow Command::getPermissionMessage() to return null
  src/pocketmine/command/Command.php
Labels: Category: Plugin API, PR: Bug Fix
