Repository pmmp/PocketMine-MP, pull requests merged in 2018-11, with the labels that each got.

#2497 Added a ClosureTask implementation for easier task scheduling
  src/pocketmine/scheduler/ClosureTask.php
  src/pocketmine/utils/Utils.php
Labels: Category: API, PR: Contribution

#2495 Remove support for source-code installations from start.* scripts
  start.cmd
  start.ps1
  start.sh
Labels: Category: User Interface, PR: Bug Fix

#2523 Return Item instance for enchant related functions
  src/pocketmine/item/Item.php
Labels: BC break, Category: API, PR: Contribution

#2525 Remove EventExecutor, event handlers now use closures internally
  src/pocketmine/event/HandlerList.php
  src/pocketmine/plugin/EventExecutor.php
  src/pocketmine/plugin/MethodEventExecutor.php
  src/pocketmine/plugin/PluginManager.php
  src/pocketmine/plugin/RegisteredListener.php
Labels: Category: API, Category: Core, PR: Contribution, PR: Optimization

#2527 Exploit PHP copy-on-write behaviour to reduce chunk memory usage by 20-40%
  src/pocketmine/level/format/Chunk.php
  src/pocketmine/level/format/SubChunk.php
Labels: Category: Core, PR: Optimization

#2534 Force minimum uptime to be >= 120 seconds if the server crashes
  src/pocketmine/Server.php
Labels: Category: Core, PR: Bug Fix
