Repository pmmp/PocketMine-MP, pull requests merged in 2018-12, with the labels that each got.

#2547 Liquid: Add events to allow controlling flow and fusion
  src/pocketmine/block/Liquid.php
Labels: Category: API, PR: Contribution

#2558 Backport usage of SetLocalPlayerAsInitializedPacket to 3.4
  src/pocketmine/Player.php
  src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter.php
Labels: Category: API, Category: Client (all), PR: Bug Fix

#2613 Allow plugins to disable background generation
  src/pocketmine/Server.php
Labels: Category: API, PR: Contribution

#2555 Introduce a "block write-batch" concept
  src/pocketmine/block/Door.php
  src/pocketmine/block/DoublePlant.php
  src/pocketmine/level/BlockWriteBatch.php
  src/pocketmine/level/generator/object/SpruceTree.php
  src/pocketmine/level/generator/object/Tree.php
Labels: Category: API, Category: Core, PR: Bug Fix, PR: Contribution
