Repository pmmp/PocketMine-MP, pull requests merged in 2018-05, with the labels that each got.

#2162 Skip method if Listener declares method with undefined argument type
  src/pocketmine/plugin/PluginManager.php
Labels: Category: API, PR: Contribution

#2164 Implemented @notHandler annotation for event handlers - skip register…
  src/pocketmine/plugin/PluginManager.php
Labels: Category: API, PR: Contribution

#2171 Allow threads to signal the server to wake it up during tick sleeps
  composer.json
  composer.lock
  src/pocketmine/Server.php
  src/pocketmine/command/CommandReader.php
  src/pocketmine/network/Network.php
  src/pocketmine/network/mcpe/RakLibInterface.php
Labels: Category: Core, PR: Contribution, PR: Optimization, Priority: High, Status: Insufficiently Tested

#2177 Fix DoubleSlab block name
  src/pocketmine/block/DoubleSlab.php
Labels: Category: Core, PR: Bug Fix
