Repository pmmp/PocketMine-MP, pull requests merged in 2019-03, with the labels that each got.

#2797 Update PlayerRespawnEvent.php
  src/pocketmine/event/player/PlayerRespawnEvent.php
Labels: Category: API, PR: Cosmetic

#2798 Flatten wall_banner and wall_sign into single blocks
  src/pocketmine/block/Banner.php
  src/pocketmine/block/BlockFactory.php
  src/pocketmine/block/Sign.php
  src/pocketmine/block/WallBanner.php
  src/pocketmine/block/WallSign.php
  src/pocketmine/block/utils/BannerPattern.php
  src/pocketmine/event/block/SignChangeEvent.php
  src/pocketmine/network/mcpe/handler/SimpleSessionHandler.php
  src/pocketmine/tile/Banner.php
  src/pocketmine/tile/Sign.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Core, PR: Contribution, Type: Request for Comments

#2769 ItemEntity: introduce controls for despawn timers
  src/pocketmine/entity/object/ItemEntity.php
Labels: Category: API, PR: Contribution, Status: Insufficiently Tested

#2823 Remove /reload
  src/pocketmine/Server.php
  src/pocketmine/command/SimpleCommandMap.php
  src/pocketmine/command/defaults/ReloadCommand.php
Labels: Category: Core, Category: User Interface, PR: Contribution

#2783 Implemented plugin loading whitelist/blacklist by config file
  .gitignore
  resources/plugin_list.yml
  src/pocketmine/Server.php
  src/pocketmine/plugin/PluginGraylist.php
  src/pocketmine/plugin/PluginManager.php
Labels: Category: Core, Category: User Interface, PR: Contribution, Status: Insufficiently Tested, Status: Work in Progress
