Repository pmmp/PocketMine-MP, pull requests merged in 2019-05, with the labels that each got.

#2901 Implement a locking variable to circumvent a infinite regression
  src/pocketmine/entity/Entity.php
Labels: Category: API, PR: Bug Fix

#2906 Changed ignoreCancelled opt-in to handleCancelled opt-in
  src/pocketmine/event/Listener.php
  src/pocketmine/plugin/PluginManager.php
  src/pocketmine/plugin/RegisteredListener.php
Labels: BC break, Category: API

#2948 Randomize the order of plugins retrieved from disk, fixes #2945
  src/pocketmine/plugin/PluginManager.php
Labels: Category: Core, PR: Bug Fix
