Repository pmmp/PocketMine-MP, pull requests merged in 2019-10, with the labels that each got.

#3131 Fixed decoding form responses with double commas inside quotes
  src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter.php
Labels: Category: Client, Type: Bug Fix, Type: Hack for Client Bug

#3132 EventPacket: Added some missing constants
  src/pocketmine/network/mcpe/protocol/EventPacket.php
Labels: Category: Protocol, Type: Contribution

#3123 Improve bucket API
  src/item/LiquidBucket.php
Labels: Category: API, Type: Contribution

#3145 Added encode/decode for some packets
  src/pocketmine/network/mcpe/NetworkBinaryStream.php
  src/pocketmine/network/mcpe/protocol/StructureTemplateDataExportRequestPacket.php
  src/pocketmine/network/mcpe/protocol/StructureTemplateDataExportResponsePacket.php
  src/pocketmine/network/mcpe/protocol/types/StructureSettings.php
Labels: Category: Protocol, Type: Contribution

#3160 Plugin::getLogger() interface no longer depends on PluginLogger
  src/plugin/Plugin.php
  src/plugin/PluginBase.php
Labels: BC break, Category: API, Type: Contribution
