Repository pmmp/PocketMine-MP, pull requests merged in 2020-12, with the labels that each got.

#3950 register HellBiome
  src/pocketmine/level/biome/Biome.php
Labels: Category: Core, Type: Bug Fix

#3942 Added a DedicatedQueryNetworkInterface to ensure Query functionality …
  src/Server.php
  src/network/query/DedicatedQueryNetworkInterface.php
Labels: Category: Network, Status: Insufficiently Tested, Type: Bug Fix

#3967 Fix that a hoe gets damage applied to it, when it's used to break a block
  src/pocketmine/block/BlockToolType.php
  src/pocketmine/block/Sponge.php
  src/pocketmine/item/Hoe.php
Labels: Category: API, Category: Gameplay, Type: Bug Fix
