Repository pmmp/PocketMine-MP, pull requests merged in 2020-05, with the labels that each got.

#3469 Utils: fix parsing of single-line doc comments, closes #3388
  src/pocketmine/utils/Utils.php
  tests/phpstan/configs/phpstan-bugs.neon
  tests/phpunit/utils/UtilsTest.php
Labels: Category: API, Category: Core, Type: Bug Fix

#3498 Task: Remove currentTick parameter
  src/scheduler/CancellableClosureTask.php
  src/scheduler/ClosureTask.php
  src/scheduler/Task.php
  src/scheduler/TaskHandler.php
  src/scheduler/TaskScheduler.php
  tests/plugins/TesterPlugin/src/pmmp/TesterPlugin/CheckTestCompletionTask.php
Labels: BC break, Category: API, Type: Contribution, Type: Request for Comments

#3502 Fix timings calculation bug in PermissionManager
  src/pocketmine/permission/PermissionManager.php
Labels: Category: Core, Type: Bug Fix

#3385 Change Level::TIME_ constants to match client
  src/pocketmine/level/Level.php
Labels: Category: API, Category: Gameplay, Type: Contribution

#3470 Players no longer burn when hit by other players
  src/pocketmine/entity/Living.php
Labels: Category: Gameplay, Status: Lacks Information, Type: Bug Fix

#3501 Improved support for paths with backslashes on Unix filesystems
  src/pocketmine/plugin/PluginBase.php
  src/pocketmine/utils/Utils.php
Labels: Category: Core, Type: Bug Fix

#3492 Fix walk sounds
  src/pocketmine/Player.php
  src/pocketmine/entity/Entity.php
Labels: Category: Gameplay, Category: Protocol, Type: Bug Fix

#3167 Player: remove move buffering, implement simple rate limited movement…
  src/pocketmine/Player.php
Labels: BC break, Category: Gameplay, Type: Contribution, Type: Request for Comments
