Repository pmmp/PocketMine-MP, pull requests merged in 2021-12, with the labels that each got.

#4613 getType() of SplashPotion
  src/item/SplashPotion.php
Labels: Category: API, Type: Contribution

#4563 Player: allow controlling client-sided block collisions irrespective of Spectator Mode
  src/network/mcpe/NetworkSession.php
  src/player/Player.php
Labels: Category: API, Type: Contribution

#4419 Implement ItemEntity merging.
  src/entity/animation/ItemEntityStackSizeChangeAnimation.php
  src/entity/object/ItemEntity.php
  src/event/entity/ItemMergeEvent.php
Labels: Category: Gameplay, Type: Contribution, Status: Insufficiently Tested, Status: Waiting on Author

#4619 ClearCommand: Cleanup logic & fix vanilla disparities
  changelogs/4.0.md
  src/command/defaults/ClearCommand.php
Labels: Category: Core, Type: Contribution

#4638 Add gamemode strings as valid values for gamemode property
  src/Server.php
  src/command/defaults/DefaultGamemodeCommand.php
  src/wizard/SetupWizard.php
Labels: Type: Contribution, Category: UI

#4623 Add ExperienceOrb attracts lock feature
  src/entity/ExperienceManager.php
  src/entity/object/ExperienceOrb.php
Labels: Category: API, Type: Contribution

#4617 Implemented fire spread (take 2)
  src/block/Fire.php
  tests/phpstan/configs/actual-problems.neon
Labels: Category: Gameplay, Type: Contribution

#4446 Implement swimming/gliding including AABB recalculation
  src/entity/Entity.php
  src/entity/Living.php
  src/event/player/PlayerToggleGlideEvent.php
  src/event/player/PlayerToggleSwimEvent.php
  src/network/mcpe/handler/InGamePacketHandler.php
  src/player/Player.php
Labels: Category: API, Category: Gameplay, Type: Contribution

#4666 Implement BlockMeltEvent
  src/block/Ice.php
  src/block/SnowLayer.php
  src/event/block/BlockMeltEvent.php
Labels: Category: API, Type: Contribution

#4670 Added gold(§g) color support
  src/utils/Terminal.php
  src/utils/TextFormat.php
Labels: Category: API, Type: Contribution
