Repository pmmp/PocketMine-MP, pull requests merged in 2021-11, with the labels that each got.

#4554 Implemented IPv6 support
  src/PocketMine.php
  src/Server.php
  src/command/defaults/BanIpCommand.php
  src/command/defaults/PardonIpCommand.php
  src/network/mcpe/raklib/RakLibInterface.php
  src/network/query/DedicatedQueryNetworkInterface.php
  src/network/query/QueryHandler.php
Labels: Type: Contribution, Category: Network

#4573 Add correct drop for Podzol
  src/block/Podzol.php
Labels: Category: Gameplay, Type: Bug Fix

#4574 Fix position of setworldspawn command
  src/command/defaults/SetWorldSpawnCommand.php
Labels: Category: Gameplay, Type: Bug Fix, Category: UI

#4591 Skull: improve calculation of collision boxes
  src/block/Skull.php
Labels: Category: Gameplay, Type: Bug Fix
