Repository pmmp/PocketMine-MP, pull requests merged in 2021-06, with the labels that each got.

#4241 Save and load arrow critical state with world
  src/entity/EntityFactory.php
  src/entity/projectile/Arrow.php
Labels: Category: Gameplay, Type: Contribution

#4246 Remove movement workaround from 1.14.30
  src/pocketmine/entity/Human.php
Labels: Category: Client, Category: Protocol, Status: Insufficiently Tested, Type: Contribution

#4238 Check Enderchest tile for viewer count
  src/block/EnderChest.php
  src/block/inventory/AnimatedBlockInventoryTrait.php
  src/block/inventory/EnderChestInventory.php
  src/block/tile/EnderChest.php
Labels: Category: Gameplay, Type: Contribution

#4240 Leaves can now be silk touched
  src/block/Leaves.php
Labels: Category: Gameplay, Type: Contribution

#4237 Better sorting of items in InventoryHelpersTrait::addItem()
  src/inventory/InventoryHelpersTrait.php
  tests/phpunit/inventory/BaseInventoryTest.php
Labels: Category: API, Status: Insufficiently Tested, Type: Contribution

#4283 InventoryHelpersTrait::AddItem() cannot add items with a count greater than maxstack
  src/inventory/InventoryHelpersTrait.php
  tests/phpunit/inventory/BaseInventoryTest.php
Labels: Category: API, Category: Gameplay, Type: Bug Fix

#4287 Start using webmozart/pathutil for joining paths
  composer.json
  composer.lock
  src/CrashDump.php
  src/MemoryManager.php
  src/PocketMine.php
  src/Server.php
  src/command/defaults/DumpMemoryCommand.php
  src/command/defaults/TimingsCommand.php
  src/data/bedrock/LegacyBlockIdToStringIdMap.php
  src/data/bedrock/LegacyEntityIdToStringIdMap.php
  src/data/bedrock/LegacyItemIdToStringIdMap.php
  src/inventory/CreativeInventory.php
  src/item/LegacyStringToItemParser.php
  src/lang/Language.php
  src/network/mcpe/cache/StaticPacketCache.php
  src/network/mcpe/convert/GlobalItemTypeDictionary.php
  src/network/mcpe/convert/ItemTranslator.php
  src/network/mcpe/convert/RuntimeBlockMapping.php
  src/plugin/PluginBase.php
  src/plugin/PluginManager.php
  src/resourcepacks/ResourcePackManager.php
  src/scheduler/DumpWorkerMemoryTask.php
  src/utils/Config.php
  src/utils/Filesystem.php
  src/wizard/SetupWizard.php
  src/world/WorldManager.php
  src/world/format/io/FormatConverter.php
  src/world/format/io/leveldb/LevelDB.php
  src/world/format/io/region/RegionWorldProvider.php
  src/world/format/io/region/WritableRegionWorldProvider.php
  tests/phpunit/world/format/io/region/RegionLoaderTest.php
Labels: Category: Core, Status: Insufficiently Tested, Type: Contribution
