Repository pmmp/PocketMine-MP, pull requests merged in 2021-07, with the labels that each got.

#3678 Add Shulker Boxes
  src/block/BlockFactory.php
  src/block/DyedShulkerBox.php
  src/block/ShulkerBox.php
  src/block/VanillaBlocks.php
  src/block/inventory/ShulkerBoxInventory.php
  src/block/tile/ShulkerBox.php
  src/block/tile/TileFactory.php
  src/world/sound/ShulkerCloseSound.php
  src/world/sound/ShulkerOpenSound.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Contribution

#4164 sweet berries
  src/block/BlockFactory.php
  src/block/SweetBerryBush.php
  src/block/VanillaBlocks.php
  src/item/ItemFactory.php
  src/item/SweetBerries.php
  src/item/VanillaItems.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Contribution

#4328 Use OpenSSL for ECDH during client login, drop mdanter/ecc
  composer.json
  composer.lock
  phpstan.neon.dist
  src/network/mcpe/JwtUtils.php
  src/network/mcpe/NetworkSession.php
  src/network/mcpe/auth/ProcessLoginTask.php
  src/network/mcpe/encryption/EncryptionUtils.php
  src/network/mcpe/encryption/PrepareEncryptionTask.php
  src/network/mcpe/handler/LoginPacketHandler.php
  tests/phpstan/configs/l8-baseline.neon
  tests/phpstan/stubs/phpasn1.stub
Labels: Category: Network, Performance, Type: Contribution

#4332 Use a subprocess for reading lines from STDIN
  src/console/ConsoleReaderChildProcess.php
  src/console/ConsoleReaderThread.php
  tests/phpstan/configs/phpstan-bugs.neon
Labels: Category: Core, Category: UI, Type: Bug Fix, Type: Contribution, Type: Enhancement
