Repository pmmp/PocketMine-MP, pull requests merged in 2021-08, with the labels that each got.

#4344 Fix item losing when player disconnect
  src/pocketmine/Player.php
Labels: Category: Gameplay, Type: Bug Fix

#4356 Bows can now use offhand arrows
  src/item/Bow.php
Labels: Category: Gameplay, Type: Contribution

#4362 Implemented Blast Furnace and Smoker
  src/block/BlockFactory.php
  src/block/VanillaBlocks.php
  src/block/inventory/FurnaceInventory.php
  src/block/tile/BlastFurnace.php
  src/block/tile/Furnace.php
  src/block/tile/NormalFurnace.php
  src/block/tile/Smoker.php
  src/block/tile/TileFactory.php
  src/crafting/CraftingManager.php
  src/crafting/CraftingManagerFromDataHelper.php
  src/crafting/FurnaceType.php
  src/network/mcpe/InventoryManager.php
  src/network/mcpe/cache/CraftingDataCache.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Contribution

#4376 Introduce GitHub Actions to automatically build and upload release artifacts, and to auto-update update.pmmp.io
  .github/workflows/draft-release.yml
  .github/workflows/update-updater-api.yml
  build/generate-build-info-json.php
  build/make-release.php
  composer.json
  src/pocketmine/VersionInfo.php
  tests/phpstan/configs/l8-baseline.neon
Labels: Type: Contribution, Category: Other

#4384 remove InventoryPickup*Event, add EntityItemPickupEvent
  src/entity/object/ItemEntity.php
  src/entity/projectile/Arrow.php
  src/event/entity/EntityItemPickupEvent.php
  src/event/inventory/InventoryPickupArrowEvent.php
  src/event/inventory/InventoryPickupItemEvent.php
Labels: Category: API, Type: Contribution, BC break, Line: Bleeding Edge

#4360 Picked up items can now be added to offhand slots.
  src/entity/object/ItemEntity.php
  src/entity/projectile/Arrow.php
Labels: Category: Gameplay, Type: Contribution, Line: Bleeding Edge

#4374 Implement Player -> Entity interaction (revival)
  src/entity/Entity.php
  src/event/player/PlayerEntityInteractEvent.php
  src/player/Player.php
Labels: Category: API, Type: Contribution, Line: Bleeding Edge

#4354 StructureGrowEvent
  src/block/Bamboo.php
  src/block/BambooSapling.php
  src/block/Sapling.php
  src/event/block/StructureGrowEvent.php
  src/world/generator/object/BirchTree.php
  src/world/generator/object/OakTree.php
  src/world/generator/object/SpruceTree.php
  src/world/generator/object/Tree.php
Labels: Category: API, Type: Contribution

#4402 BlockItemPickupEvent
  src/event/block/BlockItemPickupEvent.php
Labels: Category: API, Type: Contribution, Line: Bleeding Edge
