Repository pmmp/PocketMine-MP, pull requests merged in 2021-03, with the labels that each got.

#3378 Implement UPnP support without dotNET
  composer.json
  composer.lock
  phpstan.neon.dist
  src/pocketmine/network/upnp/UPnP.php
  src/pocketmine/resources/pocketmine.yml
  tests/phpstan/configs/com-dotnet-magic.neon
Labels: Category: Network, Type: Contribution, Type: Enhancement

#4087 Fixed player spawning in ungenerated terrain
  src/Server.php
  src/network/mcpe/NetworkSession.php
  src/player/Player.php
  src/player/PlayerCreationPromise.php
  src/world/ChunkPopulationPromise.php
  src/world/World.php
  src/world/WorldManager.php
Labels: BC break, Category: API, Category: Core, Status: Insufficiently Tested, Type: Bug Fix, Type: Contribution

#4101 fix ItemFrames
  src/pocketmine/Player.php
  tests/phpstan/configs/l8-baseline.neon
Labels: Category: Client, Category: Gameplay, Type: Bug Fix
