Repository pmmp/PocketMine-MP, pull requests merged in 2022-08, with the labels that each got.

#5226 BlockFormEvent: Added getCausingBlock() method
  src/block/ConcretePowder.php
  src/block/Liquid.php
  src/event/block/BlockFormEvent.php
Labels: Category: API, Type: Contribution, BC break

#4681 SimpleCommandMap: Enforce command permissions by default
  src/command/PluginCommand.php
  src/command/SimpleCommandMap.php
  src/command/defaults/BanCommand.php
  src/command/defaults/BanIpCommand.php
  src/command/defaults/BanListCommand.php
  src/command/defaults/ClearCommand.php
  src/command/defaults/DefaultGamemodeCommand.php
  src/command/defaults/DeopCommand.php
  src/command/defaults/DifficultyCommand.php
  src/command/defaults/DumpMemoryCommand.php
  src/command/defaults/EffectCommand.php
  src/command/defaults/EnchantCommand.php
  src/command/defaults/GamemodeCommand.php
  src/command/defaults/GarbageCollectorCommand.php
  src/command/defaults/GiveCommand.php
  src/command/defaults/HelpCommand.php
  src/command/defaults/KickCommand.php
  src/command/defaults/KillCommand.php
  src/command/defaults/ListCommand.php
  src/command/defaults/MeCommand.php
  src/command/defaults/OpCommand.php
  src/command/defaults/PardonCommand.php
  src/command/defaults/PardonIpCommand.php
  src/command/defaults/ParticleCommand.php
  src/command/defaults/PluginsCommand.php
  src/command/defaults/SaveCommand.php
  src/command/defaults/SaveOffCommand.php
  src/command/defaults/SaveOnCommand.php
  src/command/defaults/SayCommand.php
  src/command/defaults/SeedCommand.php
  src/command/defaults/SetWorldSpawnCommand.php
  src/command/defaults/SpawnpointCommand.php
  src/command/defaults/StatusCommand.php
  src/command/defaults/StopCommand.php
  src/command/defaults/TeleportCommand.php
  src/command/defaults/TellCommand.php
  src/command/defaults/TimeCommand.php
  src/command/defaults/TimingsCommand.php
  src/command/defaults/TitleCommand.php
  src/command/defaults/TransferServerCommand.php
  src/command/defaults/VersionCommand.php
  src/command/defaults/WhitelistCommand.php
Labels: Category: API, Category: Core, Type: Contribution

#5224 Implement Suspicious Stew
  build/generate-runtime-enum-serializers.php
  src/data/bedrock/SuspiciousStewTypeIdMap.php
  src/data/bedrock/SuspiciousStewTypeIds.php
  src/data/bedrock/item/ItemDeserializer.php
  src/data/bedrock/item/ItemSerializer.php
  src/data/runtime/RuntimeEnumDeserializerTrait.php
  src/data/runtime/RuntimeEnumSerializerTrait.php
  src/item/ItemTypeIds.php
  src/item/StringToItemParser.php
  src/item/SuspiciousStew.php
  src/item/SuspiciousStewType.php
  src/item/VanillaItems.php
Labels: Category: Gameplay, Type: Contribution, Status: Waiting on Author

#4690 Dye now can be used to change Sign text color
  src/block/BaseSign.php
  src/block/tile/Sign.php
  src/block/utils/SignText.php
  src/world/sound/DyeUseSound.php
  src/world/sound/InkSacUseSound.php
Labels: Category: Gameplay, Type: Contribution

#5053 Vines can now only be placed on full cube blocks.
  src/block/Vine.php
Labels: Category: Gameplay, Type: Bug Fix

#5055 Limit valid supporting blocks of dead bush
  src/block/DeadBush.php
Labels: Category: Gameplay, Type: Bug Fix

#5227 PluginManager: Ensure dependents are disabled before dependencies in …
  src/plugin/PluginManager.php
Labels: Category: API, Type: Contribution
