Repository pmmp/PocketMine-MP, pull requests merged in 2022-12, with the labels that each got.

#5444 Only reduce durability when armor reduced damage.
  src/entity/Living.php
Labels: Category: Gameplay, Type: Fix

#5428 Add the event: WorldParticleEvent
  src/event/world/WorldParticleEvent.php
  src/world/World.php
Labels: Category: API, Type: Enhancement

#5345 Implement anvil damage on fall
  src/block/Anvil.php
  src/block/utils/Fallable.php
  src/block/utils/FallableTrait.php
  src/entity/object/FallingBlock.php
Labels: Category: API, Category: Gameplay, BC break, Status: Waiting on Author, Type: Enhancement

#5432 Implemented method `onInteractEntity`
  src/item/Item.php
  src/player/Player.php
Labels: Category: API, Status: Waiting on Author, Type: Enhancement

#5395 Added keep on death methods for items
  src/entity/Human.php
  src/item/Item.php
  src/player/Player.php
Labels: Category: API, Category: Gameplay, Type: Enhancement

#5348 Implement FallingBlock missing sounds
  src/block/Anvil.php
  src/block/utils/Fallable.php
  src/block/utils/FallableTrait.php
  src/entity/object/FallingBlock.php
Labels: Category: Gameplay, BC break, Type: Enhancement

#5433 Implement new records
  src/block/utils/RecordType.php
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/item/StringToItemParser.php
  src/item/VanillaItems.php
Labels: Category: Gameplay, Type: Enhancement

#5454 Implemented chain
  src/block/BlockTypeIds.php
  src/block/Chain.php
  src/block/VanillaBlocks.php
  src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
  src/data/bedrock/block/convert/BlockStateToObjectDeserializer.php
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/item/StringToItemParser.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Status: Waiting on Author, Type: Enhancement

#5386 Show death message on death screen
  src/network/mcpe/NetworkSession.php
  src/network/mcpe/handler/DeathPacketHandler.php
  src/player/Player.php
Labels: Category: Gameplay, Status: Waiting on Author, Type: Enhancement

#5470 Add `.self` and `.other` permissions for gameplay-altering commands
  src/command/defaults/ClearCommand.php
  src/command/defaults/EffectCommand.php
  src/command/defaults/EnchantCommand.php
  src/command/defaults/GamemodeCommand.php
  src/command/defaults/GiveCommand.php
  src/command/defaults/KillCommand.php
  src/command/defaults/SpawnpointCommand.php
  src/command/defaults/TeleportCommand.php
  src/command/defaults/TitleCommand.php
  src/command/defaults/VanillaCommand.php
  src/network/mcpe/NetworkSession.php
  src/permission/DefaultPermissionNames.php
  src/permission/DefaultPermissions.php
Labels: Type: Enhancement, Category: UI

#5450 Implement Medicine
  build/generate-runtime-enum-serializers.php
  src/data/bedrock/MedicineTypeIdMap.php
  src/data/bedrock/MedicineTypeIds.php
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/data/runtime/RuntimeEnumDeserializerTrait.php
  src/data/runtime/RuntimeEnumSerializerTrait.php
  src/item/ItemTypeIds.php
  src/item/Medicine.php
  src/item/MedicineType.php
  src/item/StringToItemParser.php
  src/item/VanillaItems.php
Labels: Category: Gameplay, Type: Enhancement
