Repository pmmp/PocketMine-MP, pull requests merged in 2022-09, with the labels that each got.

#5149 Do not always make the coral dead immediately after placement
  src/block/BaseCoral.php
  src/block/FloorCoralFan.php
  src/block/WallCoralFan.php
Labels: Category: Gameplay, Type: Bug Fix, Mojang inconsistency

#5102 Add sendToast method, API to send toast with ToastRequestPacket
  src/network/mcpe/NetworkSession.php
  src/player/Player.php
Labels: Category: API, Type: Contribution, Status: Waiting on Author, Line: Experimental

#5158 Play burp sound when consuming a FoodSource
  src/entity/Living.php
  src/world/sound/BurpSound.php
Labels: Category: Gameplay, Type: Contribution, Line: Stable

#5311 ConsoleCommandSender is no longer responsible for forwarding broadcas…
  src/Server.php
  src/command/Command.php
  src/utils/BroadcastLoggerForwarder.php
Labels: Category: Core, Type: Contribution

#5268 Introduce and use TextFormat::addBase()
  src/Server.php
  src/command/defaults/GarbageCollectorCommand.php
  src/command/defaults/HelpCommand.php
  src/command/defaults/MeCommand.php
  src/command/defaults/PluginsCommand.php
  src/command/defaults/StatusCommand.php
  src/command/defaults/VersionCommand.php
  src/console/ConsoleCommandSender.php
  src/utils/MainLogger.php
  src/utils/TextFormat.php
Labels: Category: API, Type: Bug Fix, Type: Contribution, Category: UI

#4930 Fix sugarcane behaviour on fertilizers
  src/block/Sugarcane.php
Labels: Category: Gameplay, Type: Bug Fix, Type: Contribution, Line: Experimental

#5297 Allow specifying a key for encrypted resource packs
  resources/resource_packs.yml
  src/network/mcpe/handler/ResourcePacksPacketHandler.php
  src/resourcepacks/ResourcePackManager.php
Labels: Type: Contribution, Category: UI

#5147 Fix the copper block scrape sound
  src/block/utils/CopperTrait.php
  src/world/sound/ScrapeSound.php
Labels: Category: Gameplay, Type: Bug Fix, Type: Contribution, Line: Bleeding Edge

#5235 Implement Turtle Shell
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/entity/Living.php
  src/item/Item.php
  src/item/ItemTypeIds.php
  src/item/StringToItemParser.php
  src/item/TurtleHelmet.php
  src/item/VanillaItems.php
Labels: Category: Gameplay, Type: Contribution, Line: Bleeding Edge

#5054 Mushroom: checking the light for placement
  src/block/RedMushroom.php
  tests/phpstan/configs/actual-problems.neon
Labels: Category: Gameplay, Type: Contribution

#5161 Correct knockback from explosions
  src/world/Explosion.php
Labels: Category: Gameplay, Type: Contribution, Status: Waiting on Author, Line: Stable

#5314 Entity: Fire EntitySpawnEvent/ItemSpawnEvent on the first entity tick…
  src/entity/Entity.php
  src/entity/object/ItemEntity.php
  src/player/Player.php
Labels: Category: API, Category: Core, Type: Bug Fix
