Repository pmmp/PocketMine-MP, pull requests merged in 2022-11, with the labels that each got.

#5380 Fixed totem activating when having 1HP instead of 0HP
  src/entity/Human.php
Labels: Category: Gameplay, Type: Bug Fix

#5394 Correct calculation for non-arrow projectiles
  src/entity/projectile/Arrow.php
  src/entity/projectile/Projectile.php
Labels: Category: Gameplay, Type: Bug Fix

#5396 Implement Weeping & Twisting vines
  src/block/BlockTypeIds.php
  src/block/NetherVines.php
  src/block/VanillaBlocks.php
  src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
  src/data/bedrock/block/convert/BlockStateToObjectDeserializer.php
  src/item/StringToItemParser.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Contribution

#5419 Missing space
  src/network/Network.php
Labels: Type: Fix, Category: Cosmetic

#5420 Implement BlockDeathEvent
  src/block/BaseCoral.php
  src/block/CoralBlock.php
  src/event/block/BlockDeathEvent.php
Labels: Category: API, Type: Contribution

#5359 Remove unnecessary Cancellable implementation
  src/event/block/BlockGrowEvent.php
Labels: Category: API, Type: Fix

#5383 Fix missing sounds when interacting with item frames
  src/block/ItemFrame.php
  src/world/sound/ItemFrameAddItemSound.php
  src/world/sound/ItemFrameRemoveItemSound.php
  src/world/sound/ItemFrameRotateItemSound.php
Labels: Category: API, Category: Gameplay, Type: Fix, Type: Contribution

#5384 Implement a `Living::getDisplayName()`
  src/entity/Living.php
  src/event/player/PlayerDeathEvent.php
Labels: Category: API, Status: Waiting on Author, Type: Enhancement
