Repository pmmp/PocketMine-MP, pull requests merged in 2022-05, with the labels that each got.

#5019 Add stick drop chance for leaves
  src/block/Leaves.php
Labels: Category: Gameplay, Type: Contribution

#4951 Stop the server if any plugin failed to load
  src/Server.php
  src/plugin/PluginManager.php
Labels: Category: Core, Type: Contribution

#4937 Added PlayerPostChunkSendEvent
  src/event/player/PlayerPostChunkSendEvent.php
  src/player/Player.php
Labels: Category: API, Type: Contribution

#5034 Update exhaustion values.
  src/entity/Human.php
  src/entity/HungerManager.php
  src/entity/effect/HungerEffect.php
  src/player/Player.php
Labels: Category: Gameplay, Type: Contribution

#4886 Introduce support types logic
  src/block/Air.php
  src/block/Anvil.php
  src/block/Bamboo.php
  src/block/BaseBanner.php
  src/block/BaseCoral.php
  src/block/BaseRail.php
  src/block/BaseSign.php
  src/block/Bed.php
  src/block/Bell.php
  src/block/Block.php
  src/block/BrewingStand.php
  src/block/Button.php
  src/block/Cactus.php
  src/block/Cake.php
  src/block/Chest.php
  src/block/CocoaBlock.php
  src/block/Coral.php
  src/block/DaylightSensor.php
  src/block/Door.php
  src/block/DragonEgg.php
  src/block/EnchantingTable.php
  src/block/EnderChest.php
  src/block/Fence.php
  src/block/FenceGate.php
  src/block/FloorCoralFan.php
  src/block/Flowable.php
  src/block/FlowerPot.php
  src/block/Hopper.php
  src/block/Ladder.php
  src/block/Lantern.php
  src/block/Leaves.php
  src/block/Lectern.php
  src/block/Lever.php
  src/block/Liquid.php
  src/block/MonsterSpawner.php
  src/block/NetherPortal.php
  src/block/PressurePlate.php
  src/block/RedstoneComparator.php
  src/block/RedstoneRepeater.php
  src/block/RedstoneWire.php
  src/block/SeaPickle.php
  src/block/Slab.php
  src/block/SnowLayer.php
  src/block/Stair.php
  src/block/Stonecutter.php
  src/block/Thin.php
  src/block/Torch.php
  src/block/Trapdoor.php
  src/block/Wall.php
  src/block/WallCoralFan.php
  src/block/utils/SupportType.php
  tests/phpstan/configs/actual-problems.neon
Labels: Category: API, Category: Gameplay, Type: Contribution

#4780 DisablePluginException now can be used to disable plugins
  src/plugin/DisablePluginException.php
  src/plugin/PluginManager.php
Labels: Category: API, Type: Contribution

#4015 Add PlayerDeathEvent->setKeepXp() as per #4002
  src/event/player/PlayerDeathEvent.php
  src/player/Player.php
Labels: Category: API, Type: Contribution
