Repository pmmp/PocketMine-MP, pull requests merged in 2022-01, with the labels that each got.

#4685 Player: fixed fall damage when sprinting down stairs
  src/player/Player.php
Labels: Category: Gameplay, Type: Bug Fix

#4691 Fixed desynchronization of hunger
  src/network/mcpe/handler/InGamePacketHandler.php
Labels: Category: Gameplay, Category: Client, Type: Bug Fix

#4699 Fixed world spawn point not updating to players
  src/world/World.php
Labels: Category: Gameplay, Type: Bug Fix

#4708 Implemented Lectern
  src/block/BlockFactory.php
  src/block/Lectern.php
  src/block/VanillaBlocks.php
  src/block/tile/Lectern.php
  src/block/tile/TileFactory.php
  src/item/StringToItemParser.php
  src/network/mcpe/handler/InGamePacketHandler.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Contribution

#4723 Incorrect BlockBreakInfo
  src/block/BlockFactory.php
Labels: Category: Gameplay, Type: Bug Fix

#4413 Implement Brewing
  src/block/BrewingStand.php
  src/block/tile/BrewingStand.php
  src/block/utils/BrewingStandSlot.php
  src/crafting/BrewingRecipe.php
  src/crafting/CraftingManager.php
  src/crafting/CraftingManagerFromDataHelper.php
  src/crafting/PotionContainerChangeRecipe.php
  src/crafting/PotionTypeRecipe.php
  src/event/block/BrewItemEvent.php
  src/event/block/BrewingFuelUseEvent.php
  src/network/mcpe/cache/CraftingDataCache.php
  src/world/sound/PotionFinishBrewingSound.php
Labels: Category: API, Category: Gameplay, Type: Contribution

#4759 Fixed incorrect drops for Cobweb
  src/block/Cobweb.php
Labels: Category: Gameplay, Type: Bug Fix
