Repository pmmp/PocketMine-MP, pull requests merged in 2022-03, with the labels that each got.

#4774 Whitelist command now kicks non-whitelisted online players
  src/command/defaults/WhitelistCommand.php
Labels: Type: Contribution, Category: UI

#4610 Humans can now do emotes
  src/entity/Human.php
  src/network/mcpe/NetworkSession.php
  src/player/Player.php
Labels: Category: API, Type: Contribution

#4876 Sweet Berry Bush now absorbs fall damage
  src/block/SweetBerryBush.php
Labels: Category: Gameplay, Type: Bug Fix

#4816 Fixed mycelium spreading
  src/block/Mycelium.php
Labels: Category: Gameplay, Type: Bug Fix
