Repository pmmp/PocketMine-MP, pull requests merged in 2023-11, with the labels that each got.

#6134 Fix Iron & Gold ores not being affected by fortune
  src/block/GoldOre.php
  src/block/IronOre.php
Labels: Category: Gameplay, Type: Fix

#6122 Fix loading of sign text from vanilla world
  src/block/tile/Sign.php
Labels: Category: Core, Type: Fix

#6132 Implement Smithing Templates
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/item/ItemTypeIds.php
  src/item/StringToItemParser.php
  src/item/VanillaItems.php
Labels: Category: Gameplay, Type: Enhancement

#6153 Fix RegistryTrait documentation
  src/utils/EnumTrait.php
  src/utils/RegistryTrait.php
Labels: Type: Fix, Category: Documentation

#6123 Fix loading of Item Frame item rotation
  src/block/tile/ItemFrame.php
Labels: Category: Core, Type: Fix, Status: Insufficiently Tested

#6162 Fix pitcher pod wrongly registered as a block
  src/block/DoublePitcherCrop.php
  src/block/PitcherCrop.php
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/item/ItemTypeIds.php
  src/item/PitcherPod.php
  src/item/StringToItemParser.php
  src/item/VanillaItems.php
Labels: Category: API, Category: Core, Type: Fix
