Repository pmmp/PocketMine-MP, pull requests merged in 2023-09, with the labels that each got.

#6037 Entity: mark getNetworkTypeId as non-static
  src/entity/Entity.php
  src/entity/Human.php
  src/entity/Squid.php
  src/entity/Villager.php
  src/entity/Zombie.php
  src/entity/object/ExperienceOrb.php
  src/entity/object/FallingBlock.php
  src/entity/object/ItemEntity.php
  src/entity/object/Painting.php
  src/entity/object/PrimedTNT.php
  src/entity/projectile/Arrow.php
  src/entity/projectile/Egg.php
  src/entity/projectile/EnderPearl.php
  src/entity/projectile/ExperienceBottle.php
  src/entity/projectile/Snowball.php
  src/entity/projectile/SplashPotion.php
  src/world/sound/EntityLandSound.php
  src/world/sound/EntityLongFallSound.php
  src/world/sound/EntityShortFallSound.php
Labels: Category: API, BC break, Type: Cleanup

#6039 RuntimeDataDescriber: Support dynamically describing arbitrary enums
  .github/workflows/main.yml
  build/generate-runtime-enum-serializers.php
  src/block/Bell.php
  src/block/BigDripleafHead.php
  src/block/Dirt.php
  src/block/Froglight.php
  src/block/Lever.php
  src/block/MobHead.php
  src/block/RedMushroomBlock.php
  src/block/Slab.php
  src/block/utils/ColoredTrait.php
  src/block/utils/CopperTrait.php
  src/block/utils/CoralTypeTrait.php
  src/data/runtime/LegacyRuntimeEnumDescriberTrait.php
  src/data/runtime/RuntimeDataDescriber.php
  src/data/runtime/RuntimeDataReader.php
  src/data/runtime/RuntimeDataSizeCalculator.php
  src/data/runtime/RuntimeDataWriter.php
  src/data/runtime/RuntimeEnumDescriber.php
  src/data/runtime/RuntimeEnumDeserializerTrait.php
  src/data/runtime/RuntimeEnumMetadata.php
  src/data/runtime/RuntimeEnumSerializerTrait.php
  src/item/Banner.php
  src/item/Dye.php
  src/item/Medicine.php
  src/item/Potion.php
  src/item/SplashPotion.php
  src/item/SuspiciousStew.php
Labels: Category: Core, Type: Enhancement, Type: Cleanup

#5944 define RegistryTrait::__callStatic() var types
  src/utils/RegistryTrait.php
Labels: Category: API, BC break, Type: Enhancement

#5962 Age blocks logic moved into dedicated trait
  src/block/Cactus.php
  src/block/CaveVines.php
  src/block/ChorusFlower.php
  src/block/CocoaBlock.php
  src/block/Crops.php
  src/block/Fire.php
  src/block/FrostedIce.php
  src/block/NetherVines.php
  src/block/NetherWartPlant.php
  src/block/Sugarcane.php
  src/block/SweetBerryBush.php
  src/block/utils/AgeableTrait.php
Labels: Category: Core, Type: Cleanup

#5827 Implement Chiseled Bookshelf
  src/block/BlockTypeIds.php
  src/block/ChiseledBookshelf.php
  src/block/VanillaBlocks.php
  src/block/tile/ChiseledBookshelf.php
  src/block/tile/TileFactory.php
  src/block/utils/ChiseledBookshelfSlot.php
  src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
  src/data/bedrock/block/convert/BlockStateToObjectDeserializer.php
  src/data/runtime/RuntimeDataDescriber.php
  src/data/runtime/RuntimeDataReader.php
  src/data/runtime/RuntimeDataSizeCalculator.php
  src/data/runtime/RuntimeDataWriter.php
  src/item/StringToItemParser.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Status: Waiting on Author, Type: Enhancement
