Repository pmmp/PocketMine-MP, pull requests merged in 2023-06, with the labels that each got.

#5401 Implement glow lichen
  src/block/BlockTypeIds.php
  src/block/GlowLichen.php
  src/block/VanillaBlocks.php
  src/data/bedrock/block/BlockLegacyMetadata.php
  src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
  src/data/bedrock/block/convert/BlockStateReader.php
  src/data/bedrock/block/convert/BlockStateToObjectDeserializer.php
  src/data/bedrock/block/convert/BlockStateWriter.php
  src/data/runtime/RuntimeDataDescriber.php
  src/data/runtime/RuntimeDataReader.php
  src/data/runtime/RuntimeDataSizeCalculator.php
  src/data/runtime/RuntimeDataWriter.php
  src/item/StringToItemParser.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Status: Waiting on Author, Type: Enhancement

#5813 Accepting PacketBroadcaster interface instead of StandardPacketBroadcaster
  src/network/mcpe/StandardEntityEventBroadcaster.php
Labels: Category: Network, Type: Enhancement

#5806 AsyncTask Avoid useless progressUpdates allocations
  src/scheduler/AsyncPool.php
  src/scheduler/AsyncTask.php
Labels: Category: Core, Type: Enhancement, Performance

#5839 Implement Piglin Head/Skull
  src/block/utils/MobHeadType.php
  src/data/bedrock/MobHeadTypeIdMap.php
  src/data/runtime/RuntimeEnumDeserializerTrait.php
  src/data/runtime/RuntimeEnumSerializerTrait.php
  src/item/StringToItemParser.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Enhancement

#5798 Implement timings for AsyncTask completion
  src/scheduler/AsyncPool.php
  src/timings/Timings.php
Labels: Category: Core, Type: Enhancement
