Repository pmmp/PocketMine-MP, pull requests merged in 2023-01, with the labels that each got.

#5489 Implemented Sculk
  src/block/BlockTypeIds.php
  src/block/Sculk.php
  src/block/VanillaBlocks.php
  src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
  src/data/bedrock/block/convert/BlockStateToObjectDeserializer.php
  src/item/StringToItemParser.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Enhancement

#5491 Improve World::notifyNeighbourBlockUpdate() documentation
  src/world/World.php
Labels: Type: Fix, Category: Documentation

#5487 Hard code vanilla command's names in their __constructor
  src/command/SimpleCommandMap.php
  src/command/defaults/BanCommand.php
  src/command/defaults/BanIpCommand.php
  src/command/defaults/BanListCommand.php
  src/command/defaults/ClearCommand.php
  src/command/defaults/DefaultGamemodeCommand.php
  src/command/defaults/DeopCommand.php
  src/command/defaults/DifficultyCommand.php
  src/command/defaults/DumpMemoryCommand.php
  src/command/defaults/EffectCommand.php
  src/command/defaults/EnchantCommand.php
  src/command/defaults/GamemodeCommand.php
  src/command/defaults/GarbageCollectorCommand.php
  src/command/defaults/GiveCommand.php
  src/command/defaults/HelpCommand.php
  src/command/defaults/KickCommand.php
  src/command/defaults/KillCommand.php
  src/command/defaults/ListCommand.php
  src/command/defaults/MeCommand.php
  src/command/defaults/OpCommand.php
  src/command/defaults/PardonCommand.php
  src/command/defaults/PardonIpCommand.php
  src/command/defaults/ParticleCommand.php
  src/command/defaults/PluginsCommand.php
  src/command/defaults/SaveCommand.php
  src/command/defaults/SaveOffCommand.php
  src/command/defaults/SaveOnCommand.php
  src/command/defaults/SayCommand.php
  src/command/defaults/SeedCommand.php
  src/command/defaults/SetWorldSpawnCommand.php
  src/command/defaults/SpawnpointCommand.php
  src/command/defaults/StatusCommand.php
  src/command/defaults/StopCommand.php
  src/command/defaults/TeleportCommand.php
  src/command/defaults/TellCommand.php
  src/command/defaults/TimeCommand.php
  src/command/defaults/TimingsCommand.php
  src/command/defaults/TitleCommand.php
  src/command/defaults/TransferServerCommand.php
  src/command/defaults/VersionCommand.php
  src/command/defaults/WhitelistCommand.php
Labels: Category: Cosmetic, BC break, Type: Enhancement

#5505 Ring bell when is hit by a projectile
  src/block/Bell.php
Labels: Category: Gameplay, Status: Waiting on Author, Type: Enhancement
