Repository pmmp/PocketMine-MP, pull requests merged in 2023-08, with the labels that each got.

#5955 Update safe spawn API to use new world height bounds
  src/world/World.php
Labels: Category: API, Category: Core, Type: Fix

#5954 Improving performance of small moving entities (e.g. dropped items)
  src/world/World.php
Labels: Category: Gameplay, Category: Core, Status: Insufficiently Tested, Type: Enhancement, Performance

#5969 Podzol should be affected by silk touch
  src/block/Podzol.php
Labels: Category: Gameplay, Type: Fix

#5940 Implemented pink petals
  src/block/BlockTypeIds.php
  src/block/PinkPetals.php
  src/block/VanillaBlocks.php
  src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
  src/data/bedrock/block/convert/BlockStateToObjectDeserializer.php
  src/item/StringToItemParser.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Enhancement

#5916 Add FarmlandHydrationChangeEvent
  src/block/Farmland.php
  src/event/block/FarmlandHydrationChangeEvent.php
Labels: Category: API, Type: Enhancement

#5961 Added Plugin::getResourceFolder()
  src/plugin/PluginBase.php
Labels: Category: API, Type: Enhancement

#5979 Fix chorus not working below y 0
  src/item/ChorusFruit.php
Labels: Category: Gameplay, Type: Fix

#6022 Corrects errors in y-coordinate values caused in PlayerAuthInputPacket calculations
  src/network/mcpe/handler/InGamePacketHandler.php
Labels: Category: Core, Type: Fix
