Repository pmmp/PocketMine-MP, pull requests merged in 2023-03, with the labels that each got.

#5559 Implement DataPacketPreReceiveEvent
  src/event/server/DataPacketPreReceiveEvent.php
  src/network/mcpe/NetworkSession.php
Labels: Category: API, Category: Network, Type: Enhancement

#5640 replacing new Vector3(0, 0, 0) with Vector3::zero()
  src/entity/Entity.php
  src/entity/EntityDataHelper.php
  src/entity/projectile/Projectile.php
  src/event/player/PlayerInteractEvent.php
  src/player/Player.php
Labels: Category: Core, Category: Cosmetic, Type: Enhancement

#5636 First look at implementing ItemStackRequest
  composer.json
  composer.lock
  src/crafting/CraftingManager.php
  src/inventory/BaseInventory.php
  src/inventory/transaction/CraftingTransaction.php
  src/inventory/transaction/TransactionBuilderInventory.php
  src/network/mcpe/ComplexInventoryMapEntry.php
  src/network/mcpe/InventoryManager.php
  src/network/mcpe/InventoryManagerEntry.php
  src/network/mcpe/ItemStackInfo.php
  src/network/mcpe/NetworkSession.php
  src/network/mcpe/cache/CraftingDataCache.php
  src/network/mcpe/convert/TypeConverter.php
  src/network/mcpe/handler/InGamePacketHandler.php
  src/network/mcpe/handler/ItemStackContainerIdTranslator.php
  src/network/mcpe/handler/ItemStackRequestExecutor.php
  src/network/mcpe/handler/ItemStackRequestProcessException.php
  src/network/mcpe/handler/ItemStackResponseBuilder.php
  src/network/mcpe/handler/PreSpawnPacketHandler.php
Labels: Category: Core, Status: Insufficiently Tested, Category: Network, Type: Enhancement, Performance

#5312 Implement anvil fall damage
  src/block/Anvil.php
  src/block/utils/Fallable.php
  src/block/utils/FallableTrait.php
  src/entity/Living.php
  src/entity/object/FallingBlock.php
  src/event/entity/EntityDamageEvent.php
  src/event/player/PlayerDeathEvent.php
Labels: Category: API, Category: Gameplay, Type: Enhancement

#5587 Timings tree
  src/timings/TimingsHandler.php
  src/timings/TimingsRecord.php
Labels: Category: Core, Status: Insufficiently Tested, Type: Enhancement, Category: UI
