Repository pmmp/PocketMine-MP, pull requests merged in 2023-10, with the labels that each got.

#6069 fix(Entity): `broadcastSound()` not firing `WorldSoundEvent`
  src/entity/Entity.php
Labels: Category: API, Type: Fix

#6084 Fix loading of Chiseled Bookshelf tile from vanilla world
  src/block/tile/ChiseledBookshelf.php
Labels: Category: Core, Type: Fix, Priority: Critical

#6099 Wooden Button can be a fuel
  src/block/WoodenButton.php
Labels: Category: Gameplay, Type: Fix
