Repository pmmp/PocketMine-MP, pull requests merged in 2023-07, with the labels that each got.

#5694 CreativeInventory per Player
  src/inventory/transaction/action/CreateItemAction.php
  src/network/mcpe/InventoryManager.php
  src/network/mcpe/handler/ItemStackRequestExecutor.php
  src/player/Player.php
Labels: Category: API, Type: Enhancement

#5888 Implement strong slowness potion
  src/data/bedrock/PotionTypeIdMap.php
  src/data/bedrock/PotionTypeIds.php
  src/data/runtime/RuntimeEnumDeserializerTrait.php
  src/data/runtime/RuntimeEnumSerializerTrait.php
  src/item/PotionType.php
  src/item/StringToItemParser.php
Labels: Category: Gameplay, Type: Enhancement

#5892 Implement 1.20.10 short sneaking
  src/entity/Living.php
Labels: Category: Gameplay, Type: Enhancement

#5894 Don't mention enchantments in generic StringToTParser doc-comment
  src/utils/StringToTParser.php
Labels: Category: Documentation

#5757 Implement fortune enchantment
  src/block/Beetroot.php
  src/block/Carrot.php
  src/block/CoalOre.php
  src/block/CopperOre.php
  src/block/DiamondOre.php
  src/block/DoubleTallGrass.php
  src/block/EmeraldOre.php
  src/block/GildedBlackstone.php
  src/block/Glowstone.php
  src/block/Gravel.php
  src/block/LapisOre.php
  src/block/Leaves.php
  src/block/Melon.php
  src/block/NetherGoldOre.php
  src/block/NetherQuartzOre.php
  src/block/NetherVines.php
  src/block/NetherWartPlant.php
  src/block/Potato.php
  src/block/RedstoneOre.php
  src/block/SeaLantern.php
  src/block/SweetBerryBush.php
  src/block/TallGrass.php
  src/block/Wheat.php
  src/block/utils/FortuneDropHelper.php
  src/data/bedrock/EnchantmentIdMap.php
  src/item/enchantment/StringToEnchantmentParser.php
  src/item/enchantment/VanillaEnchantments.php
Labels: Category: API, Category: Gameplay, Type: Enhancement

#5835 Implemented Big & Small dripleaf
  build/generate-runtime-enum-serializers.php
  src/block/BaseBigDripleaf.php
  src/block/BigDripleafHead.php
  src/block/BigDripleafStem.php
  src/block/BlockTypeIds.php
  src/block/SmallDripleaf.php
  src/block/VanillaBlocks.php
  src/block/utils/DripleafState.php
  src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
  src/data/bedrock/block/convert/BlockStateToObjectDeserializer.php
  src/data/runtime/RuntimeEnumDescriber.php
  src/data/runtime/RuntimeEnumDeserializerTrait.php
  src/data/runtime/RuntimeEnumSerializerTrait.php
  src/data/runtime/RuntimeEnumSizeCalculatorTrait.php
  src/item/StringToItemParser.php
  src/world/sound/DripleafTiltDownSound.php
  src/world/sound/DripleafTiltUpSound.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Enhancement

#5919 Alternative fix for /kill #4680
  src/command/defaults/KillCommand.php
  src/entity/Living.php
Labels: Category: Gameplay, Type: Fix

#5830 Accept translatable permission messages in `Command`
  src/command/Command.php
Labels: Category: API, Type: Enhancement

#5486 Fix frosted ice from melting immediately
  src/block/FrostedIce.php
Labels: Category: Gameplay, Type: Fix

#5924 Fix typo in documentation of `ChunkSelector:selectChunks()`
  src/player/ChunkSelector.php
Labels: Type: Fix, Category: Documentation

#5930 Remove unnecessary HorizontalFacingTrait
  src/block/CarvedPumpkin.php
  src/block/ChemistryTable.php
  src/block/Chest.php
  src/block/EndPortalFrame.php
  src/block/EnderChest.php
  src/block/Furnace.php
  src/block/GlazedTerracotta.php
  src/block/Lectern.php
  src/block/Loom.php
  src/block/Stonecutter.php
Labels: Category: Core, Type: Cleanup
