Repository pmmp/PocketMine-MP, pull requests merged in 2023-02, with the labels that each got.

#5551 GeneratorManager: Removed redundant Closure::fromCallable wrapping
  src/world/generator/GeneratorManager.php
Labels: Category: Core, Type: Fix

#5567 start.sh: Use -n instead of ! -z
  start.sh
Labels: Category: Core, Type: Enhancement

#5553 Implemented reinforced deepslate
  src/block/BlockTypeIds.php
  src/block/VanillaBlocks.php
  src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
  src/data/bedrock/block/convert/BlockStateToObjectDeserializer.php
  src/item/StringToItemParser.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Enhancement
