Repository pmmp/PocketMine-MP, pull requests merged in 2024-09, with the labels that each got.

#6438 fix: BlueIce behavior
  src/block/BlueIce.php
Labels: Category: Gameplay, Type: Fix

#6440 Implement missing last interacted slot property in chiseled bookshelf
  src/block/ChiseledBookshelf.php
  src/block/tile/ChiseledBookshelf.php
Labels: Category: API, Category: Gameplay, Type: Enhancement

#6304 Validate transaction slots
  src/inventory/ArmorInventory.php
  src/inventory/BaseInventory.php
  src/inventory/SlotValidatedInventory.php
  src/inventory/transaction/action/SlotChangeAction.php
  src/inventory/transaction/action/validator/CallbackSlotValidator.php
  src/inventory/transaction/action/validator/SlotValidator.php
Labels: Category: API, Category: Core, Type: Enhancement

#6366 Implement new 1.21 copper blocks
  src/block/BlockTypeIds.php
  src/block/CopperBulb.php
  src/block/CopperDoor.php
  src/block/CopperGrate.php
  src/block/CopperTrapdoor.php
  src/block/VanillaBlocks.php
  src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
  src/data/bedrock/block/convert/BlockStateToObjectDeserializer.php
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/item/StringToItemParser.php
  tests/phpstan/configs/phpstan-bugs.neon
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Enhancement
