Repository pmmp/PocketMine-MP, pull requests merged in 2024-11, with the labels that each got.

#6416 Blockstate schema generator improvements
  src/data/bedrock/block/upgrade/BlockStateUpgradeSchema.php
  src/data/bedrock/block/upgrade/BlockStateUpgradeSchemaBlockRemap.php
  src/data/bedrock/block/upgrade/BlockStateUpgradeSchemaFlattenInfo.php
  src/data/bedrock/block/upgrade/BlockStateUpgradeSchemaUtils.php
  src/data/bedrock/block/upgrade/BlockStateUpgrader.php
  src/data/bedrock/block/upgrade/model/BlockStateUpgradeSchemaModel.php
  src/data/bedrock/block/upgrade/model/BlockStateUpgradeSchemaModelBlockRemap.php
  src/data/bedrock/block/upgrade/model/BlockStateUpgradeSchemaModelFlattenInfo.php
  tests/phpunit/data/bedrock/block/upgrade/BlockStateUpgraderTest.php
  tools/blockstate-upgrade-schema-utils.php
Labels: Type: Enhancement, Category: Dev Workflow

#6445 Regeneration 5 => 2 matching Java
  src/item/GoldenAppleEnchanted.php
Labels: Category: Gameplay, Type: Fix

#6444 Implement a sound when drinking a potion
  src/item/Potion.php
  src/world/sound/BottleEmptySound.php
Labels: Category: Gameplay, Type: Enhancement

#6487 Fix GC Cycle Count Increases on Player Disconnect
  src/inventory/ArmorInventory.php
Labels: Category: Core, Type: Fix

#6493 Prepare 5.21.1 release
  changelogs/5.21.md
  src/VersionInfo.php
Labels: Type: Release (!!!)

#5232 Implement Goat horns
  src/data/bedrock/GoatHornTypeIdMap.php
  src/data/bedrock/GoatHornTypeIds.php
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/item/GoatHorn.php
  src/item/GoatHornType.php
  src/item/ItemTypeIds.php
  src/item/StringToItemParser.php
  src/item/VanillaItems.php
  src/world/sound/GoatHornSound.php
Labels: Category: Gameplay, Type: Enhancement

#6498 Use reflection to locate BlockTypeIds and ItemTypeIds for VanillaBlocks/VanillaItems
  src/block/VanillaBlocks.php
  src/block/WoodLikeBlockIdHelper.php
  src/item/VanillaItems.php
  tests/phpstan/configs/phpstan-bugs.neon
  tests/phpunit/block/BlockTypeIdsTest.php
  tests/phpunit/item/ItemTypeIdsTest.php
Labels: Category: Core, Type: Enhancement

#5392 Flowable blocks now can't be placed inside liquid
  src/block/Flowable.php
Labels: Category: Gameplay, Type: Fix

#6396 Split glow lichen multi face logic into traits
  src/block/GlowLichen.php
  src/block/utils/MultiAnyFacingTrait.php
  src/block/utils/MultiAnySupportTrait.php
Labels: Category: API, Category: Core, Type: Enhancement

#6429 Implemented vanilla /xp command.
  src/command/SimpleCommandMap.php
  src/command/defaults/XpCommand.php
  src/permission/DefaultPermissionNames.php
  src/permission/DefaultPermissions.php
Labels: Category: Gameplay, Type: Enhancement

#6497 start.sh: print warnings on unusual exit codes from the server process
  start.sh
Labels: Type: Enhancement, Category: UI

#4683 PlayerInteractEvent: added APIs to independently control reaction of item and block
  src/event/player/PlayerInteractEvent.php
  src/network/mcpe/handler/InGamePacketHandler.php
  src/world/World.php
Labels: Category: API, Type: Enhancement

#4715 Implemented End Crystal
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/entity/EntityFactory.php
  src/entity/object/EndCrystal.php
  src/entity/projectile/Projectile.php
  src/item/EndCrystal.php
  src/item/ItemTypeIds.php
  src/item/StringToItemParser.php
  src/item/VanillaItems.php
Labels: Category: Gameplay, Status: Insufficiently Tested, Type: Enhancement

#6522 Fix: implicitly nullable parameter declarations deprecated in PHP 8.4
  src/world/World.php
Labels: Category: Core, Type: Fix

#6351 Adjust pretty name of closures on PHP 8.4
  src/utils/Utils.php
Labels: Category: Core, Type: Fix

#5273 ConsoleReader: Use proc_open()'s socket support to send commands back…
  src/console/ConsoleReaderChildProcess.php
  src/console/ConsoleReaderChildProcessDaemon.php
  src/console/ConsoleReaderChildProcessUtils.php
  tests/phpunit/console/ConsoleReaderChildProcessUtilsTest.php
Labels: Category: Core, Type: Enhancement

#6528 Fix insta break check
  src/player/Player.php
Labels: Category: Gameplay, Type: Fix

#6030 Add generic types for TaskHandler
  src/scheduler/Task.php
  src/scheduler/TaskHandler.php
  src/scheduler/TaskScheduler.php
  src/timings/Timings.php
  tests/phpstan/configs/actual-problems.neon
Labels: Category: API, Type: Enhancement

#5452 Implement Ice Bomb
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/entity/EntityFactory.php
  src/entity/projectile/IceBomb.php
  src/item/IceBomb.php
  src/item/ItemTypeIds.php
  src/item/StringToItemParser.php
  src/item/VanillaItems.php
  src/world/sound/IceBombHitSound.php
Labels: Category: Gameplay, Type: Enhancement

#6532 Introduce Utils::getRandomFloat()
  src/block/Anvil.php
  src/block/Farmland.php
  src/block/ItemFrame.php
  src/block/Liquid.php
  src/entity/Entity.php
  src/entity/Living.php
  src/item/Armor.php
  src/item/Durable.php
  src/item/RottenFlesh.php
  src/item/SpawnEgg.php
  src/utils/Utils.php
  src/world/World.php
Labels: Category: PHP, Type: Enhancement

#6545 Prepare patch release
  changelogs/5.21.md
  src/VersionInfo.php
Labels: Type: Release (!!!)
