Repository pmmp/PocketMine-MP, pull requests merged in 2024-08, with the labels that each got.

#6408 Implement Aqua Affinity
  src/data/bedrock/EnchantmentIdMap.php
  src/item/enchantment/AvailableEnchantmentRegistry.php
  src/item/enchantment/StringToEnchantmentParser.php
  src/item/enchantment/VanillaEnchantments.php
Labels: Category: Gameplay, Type: Enhancement

#6421 Fixed incorrect function visibility modifier in ChiseledBookshelf tile class
  src/block/tile/ChiseledBookshelf.php
Labels: Category: Core, Type: Fix

#6375 Fixed anvil placing rotation.
  src/block/Anvil.php
Labels: Category: Gameplay, Type: Fix

#6414 Fix effect bubbles not showing
  composer.json
  composer.lock
  src/entity/Living.php
Labels: Category: Gameplay, Type: Fix, Category: Protocol

#6407 Add ShellCheck
  .github/workflows/main.yml
  start.sh
  tests/travis.sh
Labels: Type: Enhancement, Category: Dev Workflow

#6433 Fix shift crafting
  src/network/mcpe/handler/ItemStackRequestExecutor.php
Labels: Category: Gameplay, Category: Core, Type: Fix
