Repository pmmp/PocketMine-MP, pull requests merged in 2024-12, with the labels that each got.

#6333 Async task timings
  composer.json
  composer.lock
  src/Server.php
  src/command/defaults/TimingsCommand.php
  src/lang/KnownTranslationFactory.php
  src/lang/KnownTranslationKeys.php
  src/scheduler/AsyncTask.php
  src/scheduler/TimingsCollectionTask.php
  src/scheduler/TimingsControlTask.php
  src/timings/Timings.php
  src/timings/TimingsHandler.php
  tests/phpstan/configs/phpstan-bugs.neon
Labels: Category: Core, Type: Enhancement, Category: UI

#6063 Added ClosureCommand
  src/command/ClosureCommand.php
Labels: Category: API, Type: Enhancement

#5502 Implement Recovery compass
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/item/ItemTypeIds.php
  src/item/StringToItemParser.php
  src/item/VanillaItems.php
  src/player/Player.php
Labels: Category: API, Category: Gameplay, Status: Insufficiently Tested, Type: Enhancement, Easy task

#5497 Implement frost walker enchantment
  src/block/Magma.php
  src/data/bedrock/EnchantmentIdMap.php
  src/entity/Living.php
  src/item/enchantment/AvailableEnchantmentRegistry.php
  src/item/enchantment/StringToEnchantmentParser.php
  src/item/enchantment/VanillaEnchantments.php
Labels: Category: Gameplay, Type: Enhancement, Easy task

#6261 feat(Server): add a setter for `maxPlayers`
  src/Server.php
Labels: Category: API, BC break, Type: Enhancement

#6559 Bedrock 1.21.50
  changelogs/5.22.md
  composer.json
  composer.lock
  src/VersionInfo.php
  src/data/bedrock/BedrockDataFiles.php
  src/data/bedrock/BiomeIds.php
  src/data/bedrock/block/BlockStateNames.php
  src/data/bedrock/block/BlockStateStringValues.php
  src/data/bedrock/block/BlockTypeNames.php
  src/data/bedrock/item/ItemTypeNames.php
  src/network/mcpe/handler/InGamePacketHandler.php
  src/network/mcpe/handler/ItemStackResponseBuilder.php
  src/network/mcpe/handler/ResourcePacksPacketHandler.php
Labels: Category: Protocol, Type: Enhancement, Status: Blocked

#6564 Fixed CrashDump incorrectly detecting phar core crashes as plugin crashes
  build/server-phar-stub.php
  src/PocketMine.php
Labels: Category: Core, Priority: High, Type: Fix

#5838 Add of new minecraft colours
  src/utils/Terminal.php
  src/utils/TextFormat.php
Labels: Category: API, Category: Gameplay, Type: Enhancement, Status: Blocked, Easy task

#6571 Implement resin blocks & items
  src/block/BlockTypeIds.php
  src/block/ResinClump.php
  src/block/VanillaBlocks.php
  src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
  src/data/bedrock/block/convert/BlockStateToObjectDeserializer.php
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/item/ItemTypeIds.php
  src/item/StringToItemParser.php
  src/item/VanillaItems.php
  tests/phpunit/block/block_factory_consistency_check.json
Labels: Category: Gameplay, Type: Enhancement

#6573 Remove some blocks tool tier to match the recent vanilla changes
  src/block/VanillaBlocks.php
Labels: Category: Gameplay, Type: Enhancement

#6554 PM managed GC
  src/MemoryManager.php
Labels: Category: Core, Status: Insufficiently Tested, Type: Enhancement, Performance
