Repository pmmp/PocketMine-MP, pull requests merged in 2024-03, with the labels that each got.

#6249 Implement player session-specific resource stacks
  src/event/player/PlayerResourcePackOfferEvent.php
  src/network/mcpe/NetworkSession.php
  src/network/mcpe/handler/ResourcePacksPacketHandler.php
  tests/phpstan/configs/actual-problems.neon
Labels: Category: API, Status: Insufficiently Tested, Type: Enhancement

#4032 Log rotate
  src/PocketMine.php
  src/utils/MainLogger.php
  src/utils/MainLoggerThread.php
  tests/phpunit/scheduler/AsyncPoolTest.php
Labels: Category: Core, Type: Enhancement

#6217 PocketMine-MP.phar self-extraction to decompressed cache
  build/server-phar-stub.php
  build/server-phar.php
  src/VersionInfo.php
Labels: Category: Core, Type: Fix, Status: Insufficiently Tested

#6298 Added new banner patterns
  src/block/utils/BannerPatternType.php
  src/data/bedrock/BannerPatternTypeIdMap.php
Labels: Category: API, Category: Gameplay, Type: Enhancement

#6299 Fix nether roots support
  src/block/NetherRoots.php
Labels: Category: Gameplay, Type: Fix
