Repository pmmp/PocketMine-MP, pull requests merged in 2025-09, with the labels that each got.

#6790 Strip unnecessary NBT from network items
  src/network/mcpe/convert/TypeConverter.php
Labels: Category: Network, Type: Enhancement, Performance

#5455 Implement firework rocket & firework star
  src/data/bedrock/FireworkRocketTypeIdMap.php
  src/data/bedrock/FireworkRocketTypeIds.php
  src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
  src/entity/animation/FireworkParticlesAnimation.php
  src/entity/object/FireworkRocket.php
  src/event/player/PlayerDeathEvent.php
  src/item/FireworkRocket.php
  src/item/FireworkRocketExplosion.php
  src/item/FireworkRocketType.php
  src/item/FireworkStar.php
  src/item/ItemTypeIds.php
  src/item/StringToItemParser.php
  src/item/VanillaItems.php
  src/world/sound/FireworkCrackleSound.php
  src/world/sound/FireworkExplosionSound.php
  src/world/sound/FireworkLargeExplosionSound.php
  src/world/sound/FireworkLaunchSound.php
Labels: Category: Gameplay, Type: Enhancement

#6801 EndCrystal: defer explosion until next tick update
  src/entity/object/EndCrystal.php
Labels: Category: Gameplay, Type: Fix
