Repository pmmp/PocketMine-MP, pull requests merged in 2025-08, with the labels that each got.

#6766 Prepare 5.32.1 release
  changelogs/5.32.md
  src/VersionInfo.php
Labels: Type: Release (!!!)

#6759 BlockObjectToStateSerializer: Avoid unnecessary Writer and Closure
  src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
Labels: Category: API, Category: Core, Type: Enhancement

#6775 Fixed hanging signs placement criteria
  src/block/BlockTypeTags.php
  src/block/CeilingCenterHangingSign.php
  src/block/CeilingEdgesHangingSign.php
  src/block/VanillaBlocks.php
  src/block/WallHangingSign.php
  src/item/HangingSign.php
  src/item/Item.php
  src/world/World.php
Labels: Category: API, Category: Gameplay, Type: Fix
