Repository pmmp/PocketMine-MP, pull requests merged in 2025-02, with the labels that each got.

#6606 Optimise collision box checks by caching some basic info
  src/block/RuntimeBlockStateRegistry.php
  src/world/World.php
Labels: Category: Core, Status: Incomplete, Type: Enhancement, Performance

#6622 Added resin material color format
  src/utils/Terminal.php
  src/utils/TextFormat.php
Labels: Category: Gameplay, Type: Enhancement, Easy task

#6627 Bedrock 1.21.60
  composer.json
  composer.lock
  src/data/bedrock/BedrockDataFiles.php
  src/data/bedrock/block/BlockStateData.php
  src/data/bedrock/block/BlockStateNames.php
  src/data/bedrock/block/BlockStateStringValues.php
  src/data/bedrock/block/convert/BlockStateDeserializerHelper.php
  src/data/bedrock/block/convert/BlockStateSerializerHelper.php
  src/entity/Human.php
  src/inventory/CreativeCategory.php
  src/inventory/CreativeGroup.php
  src/inventory/CreativeInventory.php
  src/inventory/CreativeInventoryEntry.php
  src/inventory/json/CreativeGroupData.php
  src/lang/KnownTranslationFactory.php
  src/lang/KnownTranslationKeys.php
  src/network/mcpe/InventoryManager.php
  src/network/mcpe/NetworkSession.php
  src/network/mcpe/cache/CreativeInventoryCache.php
  src/network/mcpe/cache/CreativeInventoryCacheEntry.php
  src/network/mcpe/convert/ItemTypeDictionaryFromDataHelper.php
  src/network/mcpe/handler/PreSpawnPacketHandler.php
  src/world/format/io/data/BedrockWorldData.php
  tools/generate-bedrock-data-from-packets.php
Labels: Category: API, Category: Protocol, Type: Enhancement

#6631 Prepare 5.25.0 release
  changelogs/5.25.md
  src/VersionInfo.php
Labels: Type: Release (!!!)

#6641 Update VersionInfo.php
  changelogs/5.25.md
  src/VersionInfo.php
Labels: Type: Release (!!!)
