Repository pmmp/PocketMine-MP, pull requests merged in 2025-05, with the labels that each got.

#6695 Remove `ServerEvent` class
  src/event/server/CommandEvent.php
  src/event/server/DataPacketDecodeEvent.php
  src/event/server/DataPacketReceiveEvent.php
  src/event/server/DataPacketSendEvent.php
  src/event/server/LowMemoryEvent.php
  src/event/server/NetworkInterfaceEvent.php
  src/event/server/QueryRegenerateEvent.php
  src/event/server/ServerEvent.php
  src/event/server/UpdateNotifyEvent.php
Labels: Category: API, BC break, Type: Cleanup

#6629 Unit test block hardness & blast resistance values
  src/block/BlockBreakInfo.php
  src/block/VanillaBlocks.php
  tests/phpunit/block/BlockTest.php
Labels: Category: Core, Type: Enhancement

#6673 Add EntityFrostWalkerEvent
  src/entity/Living.php
  src/event/entity/EntityFrostWalkerEvent.php
Labels: Category: API, Type: Enhancement

#6674 Rename `PlayerExhaustEvent` to `EntityExhaustEvent`
  src/entity/Human.php
  src/entity/HungerManager.php
  src/entity/effect/HungerEffect.php
  src/event/entity/EntityExhaustEvent.php
  src/player/Player.php
Labels: Category: API, BC break, Type: Cleanup

#6678 Item: make setter methods fluent
  src/item/Item.php
Labels: Category: API, BC break, Type: Enhancement
