Repository pmmp/PocketMine-MP, pull requests merged in 2025-06, with the labels that each got.

#6718 Move to newer systems for movement and block break handling
  src/network/mcpe/InventoryManager.php
  src/network/mcpe/handler/InGamePacketHandler.php
  src/network/mcpe/handler/ItemStackRequestExecutor.php
  src/network/mcpe/handler/PreSpawnPacketHandler.php
Labels: Category: Protocol, Type: Enhancement

#6742 Fixed held block placement after respawn anchor explosion
  src/block/RespawnAnchor.php
Labels: Category: Gameplay, Type: Fix

#6743 Disable client-side locator bar
  src/network/mcpe/handler/PreSpawnPacketHandler.php
Labels: Category: Gameplay, Type: Fix

#6744 Release 5.30.1
  changelogs/5.30.md
  composer.lock
  src/VersionInfo.php
Labels: Type: Release (!!!)
